name: frets
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:

  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Leland
      fonts:
        - asset: assets/fonts/Leland.otf
    - family: LelandText
      fonts:
        - asset: assets/fonts/LelandText.otf
    - family: MuseJazz
      fonts:
        - asset: assets/fonts/MuseJazz.otf
    - family: MuseJazzText
      fonts:
        - asset: assets/fonts/MuseJazzText.otf  
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
